### ISSUE TITLE
fs.cpSync not found in Node 16.3.0

### ISSUE THREAD

**Issue by bidinzky** [nickjj/esbuild-copy-static-files#2]
fs.cpSync is an experimental API that should not be used in production.
Maybe it should be changed to some stable API until it gets fixed.

**Comment by nickjj** [comment]
Hi,

This is called out in the installation part of the docs at: https://github.com/nickjj/esbuild-copy-static-files#installation. It mentions Node 16.7+ is required.

This plugin takes files from 1 directory and copies them to another directory during the build process of your assets. I've processed thousands of assets through this with varying types of directory structures and it works perfectly well. There were zero issues or cases where something wasn't copied correctly.

The experimental notice is likely in relation to maybe the API of using the function will change in the future but that's ok, it will be easy enough to handle that change at the esbuild-copy-static-files library level where end users who use this package won't need to think about it and it will work with any version of Node that's >= 16.7.
