### ISSUE TITLE
multiple source and destination configuration

### ISSUE THREAD

**Issue by atlemagnussen** [nickjj/esbuild-copy-static-files#5]
Hi,

I really like the idea of this plugin over the other copy plugins, but can it handle multiple configurations of sources and destinations?

**Comment by nickjj** [comment]
Hi,

In the README file, the basic usage example is:

```js
  plugins: [
    copyStaticFiles({
      src: './static',
      dest: '../public',
    })
  ],
```

While I haven't done it personally it should be able to support being called multiple times like this:

```js
  plugins: [
    copyStaticFiles({
      src: './static',
      dest: '../public',
    }),
    copyStaticFiles({
      src: './another/path',
      dest: '../somewhere/else',
    })
  ],
```

Let me know if that works.

**Comment by ianchanning** [comment]
Yes! I came here to compliment how nicely this plugin worked as I hoped it would.

I have an npm monorepo setup with:

```
packages/
├── client/
├── server/
├── desktop/ 
```

I wanted to copy files from the `src` in `desktop` *and* fonts from `client/src/styles/fonts`. Duplicating this in the plugins does exactly that. So I have both the ability to copy files from multiple sources and from sources outside the current package.

```js
    plugins: [
        require('esbuild-mdx')(),
        copyStaticFiles({
            src: './src',
            dest: './build',
            filter: filterFiles,
        }),
        copyStaticFiles({
            src: '../client/src/styles/fonts',
            dest: './build/styles/fonts',
        }),
    ],
```

**Comment by nickjj** [comment]
Thanks. In that case I'm going to close this issue out since there's a reasonable solution that works for the single and multiple source use case.
